### PR TITLE
Add more verse from Qur'an

### PR DESCRIPTION
**Pull request by FerdinaKusumah**
I found this extension is really helpful for me.
I want to contribute to add more verse from quran.

How i can find this verse is
I'm try to search from online verse about quotes from quran, then i'm compare with kemenag quran.
Then put in here as final result.
Insyaallah it's all correct.

### CODE REVIEW

**Comment by novalagung** [comment]
@FerdinaKusumah awesome! thank you. I will create the release asap!

**Comment by novalagung** [comment]
@FerdinaKusumah fyi, I added some modifications to the new quotes:

- remove duplicate quote (previously quote numbers `93` and `94` are duplicates)
- append the same quotes to the English version (with English translation of course)

**Comment by novalagung** [comment]
@FerdinaKusumah it's merged.

again, thank you for the contribution!

**Comment by FerdinaKusumah** [comment]
Thank you mas @novalagung next time will added also in english version also check for duplicate content.

**Pull request merged**
